# Generated by Django 4.2.4 on 2026-05-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hospital_id',
            field=models.IntegerField(blank=True, help_text='ID of the hospital this staff belongs to', null=True),
        ),
    ]
