# Generated by Django 4.2.4 on 2026-04-07 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_age', models.PositiveIntegerField()),
                ('current_diagnosis', models.TextField()),
                ('reason_for_referral', models.TextField()),
                ('required_specialty', models.CharField(max_length=100)),
                ('medical_documents', models.JSONField(default=list, help_text='List of document file paths')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_referrals', to=settings.AUTH_USER_MODEL)),
                ('receiving_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_referrals', to='hospital.hospital')),
                ('referring_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_referrals', to='hospital.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_age', models.PositiveIntegerField()),
                ('patient_gender', models.CharField(max_length=10)),
                ('case_description', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('acknowledged', 'Acknowledged'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=15)),
                ('eta', models.CharField(help_text='Estimated time of arrival', max_length=50)),
                ('distance', models.CharField(max_length=50)),
                ('ambulance_id', models.CharField(max_length=50)),
                ('tags', models.JSONField(default=list, help_text="List of tags like ['Cardiac', 'Emergency']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('receiving_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_alerts', to='hospital.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('available_beds', models.PositiveIntegerField(default=0)),
                ('total_beds', models.PositiveIntegerField(default=0)),
                ('doctors_on_duty', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='hospital.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(choices=[('ventilators', 'Ventilators'), ('defibrillators', 'Defibrillators'), ('ct', 'CT Scanner'), ('mri', 'MRI Scanner'), ('xray', 'X-Ray Machine'), ('dialysis', 'Dialysis Machine')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('total_count', models.PositiveIntegerField(default=1)),
                ('available_count', models.PositiveIntegerField(default=1)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='hospital.hospital')),
            ],
            options={
                'unique_together': {('hospital', 'equipment_type')},
            },
        ),
        migrations.CreateModel(
            name='BloodInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('units_available', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_inventory', to='hospital.hospital')),
            ],
            options={
                'unique_together': {('hospital', 'blood_type')},
            },
        ),
    ]
