# Generated by Django 4.2.4 on 2026-04-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='admin_email',
            field=models.EmailField(default='', help_text='Primary administrator email', max_length=254),
        ),
        migrations.AddField(
            model_name='hospital',
            name='bed_capacity',
            field=models.PositiveIntegerField(default=0, help_text='Total bed capacity of the hospital'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='emergency_contact',
            field=models.CharField(default='', help_text='Emergency contact person name', max_length=200),
        ),
    ]
