# Generated by Django 4.2.4 on 2026-05-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_hospital_admin_email_hospital_bed_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('ventilators', 'Ventilators'), ('defibrillators', 'Defibrillators'), ('ct', 'CT Scanner'), ('mri', 'MRI Scanner'), ('xray', 'X-Ray Machine'), ('dialysis', 'Dialysis Machine'), ('icu_monitor', 'ICU Monitor'), ('ecg', 'ECG Machine'), ('ultrasound', 'Ultrasound'), ('incubator', 'Incubator'), ('pulse_oximeter', 'Pulse Oximeter'), ('infusion_pump', 'Infusion Pump'), ('cardiac_monitor', 'Cardiac Monitor'), ('oxygen_concentrator', 'Oxygen Concentrator'), ('surgical_lights', 'Surgical Lights')], max_length=30),
        ),
    ]
